# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pipelines:
  default:
    - step:
        name: Build and test
        script:
          - npm install
          - npm test
        after-script:
          - if [[ BITBUCKET_EXIT_CODE -eq 0 ]]; then exit 0; else echo "Step failed"
          -  pipe: atlassian/email-notify:0.3.8 
             variables: 
               USERNAME: 'myemail@example.com' 
               PASSWORD: $PASSWORD 
               FROM: 'myemail@example.com' 
               TO: 'example@example.com' 
               HOST: 'smtp.gmail.com'
               BODY_PLAIN: "Build failed!"